import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { SurahProvider } from "@/lib/context/SurahContext";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="border-4 border-double border-white m-10 p-5 text-center">Quran Search</div>
        <div className="min-h-screen border border-white m-10 h-full">
          <SurahProvider>
            {children}
          </SurahProvider>
        </div>
      </body>
    </html>
  );
}
